name: publish-to-github-pages
on:
  push:
    branches:
      - Setup-Action-Build-Deploy-Workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
        uses: ./.github/workflows/setup-node

      - name: Install gh-pages
        run: npm install --save gh-pages --legacy-peer-deps

      # - name: Setup Pages âš™ï¸
      #   uses: actions/configure-pages@v4
      #   with:
      #     static_site_generator: next
      
      - name: Configure Git
        run: |
          git config --global user.email "jyhee@nh2system.com"
          git config --global user.name "jyhee-nh2"

      - name: Build ğŸ—ï¸
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          npx eslint src --fix
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          CI=false npm run deploy
          
      # - name: Upload artifact ğŸ“¡
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: ./build

  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Publish to GitHub Pages ğŸš€
  #       id: deployment
  #       uses: actions/deploy-pages@v4
